const contactsData = [
  {
    id: 1,
    firstName: "Nguyễn Văn",
    lastName: "An",
    phone: "0123456789",
    email: "nguyen.van.an@email.com",
    address: "123 Nguyễn Trãi, Hà Nội",
    company: "Công ty ABC",
    category: "Công việc",
  },
  {
    id: 2,
    firstName: "Trần Thị",
    lastName: "Bình",
    phone: "0987654321",
    email: "tran.thi.binh@email.com",
    address: "456 Lê Lợi, TP.HCM",
    company: "Công ty XYZ",
    category: "Gia đình",
  },
  {
    id: 3,
    firstName: "Lê Minh",
    lastName: "Cường",
    phone: "0369852147",
    email: "le.minh.cuong@email.com",
    address: "789 Trần Hưng Đạo, Đà Nẵng",
    company: "Freelancer",
    category: "Bạn bè",
  },
  {
    id: 4,
    firstName: "Phạm Quốc",
    lastName: "Dũng",
    phone: "0912345678",
    email: "pham.quoc.dung@email.com",
    address: "25 Hai Bà Trưng, Hải Phòng",
    company: "Công ty DEF",
    category: "Công việc",
  },
  {
    id: 5,
    firstName: "Hoàng Thu",
    lastName: "Em",
    phone: "0978123456",
    email: "hoang.thu.em@email.com",
    address: "12 Nguyễn Huệ, Huế",
    company: "Cá nhân",
    category: "Gia đình",
  },
];

export default contactsData;